<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../base.css">
</head>

<body>
  <!-- video 71 -->
  <script>
    function wait(ms = 0) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms);
      });
    }

    function makePizza(toppings = []) {
      return new Promise(function (resolve, reject) {
        // reject if people try with pineapple
        if (toppings.includes('pineapple')) {
          reject('Seriously? Get out 🍍');
        }
        const amountOfTimeToBake = 500 + toppings.length * 200;
        // wait 1 second for the pizza to cook:
        setTimeout(function () {
          // when you are ready, you can resolve this promise
          resolve(`Here is your pizza 🍕 with the toppings ${toppings.join(' ')}`);
        }, amountOfTimeToBake);
        // if something went wrong, we can reject this promise;
      });
    }

    // Error Handling methods

    // 1. try-catch method
    // async function go() {
    //   try {
    //     console.log('hey from try');
    //     window.doesNotExist();
    //     const pizza = await makePizza(['pineapple']);
    //     console.log(pizza);
    //   } catch (err) {
    //     console.log('Ohhh nooo!');
    //     console.log(err);
    //   }
    // }

    // 1. mix-match method
    // function handleError(err) {
    //   console.log('ohhh nooo');
    //   console.log(err);
    // }
    // async function go() {
    //   const pizza = await makePizza(['pineapple']).catch(handleError);
    //   console.log(pizza);
    // }
    // go();

    // function handleError(err) {
    //   console.log('ohhh nooo');
    //   console.log(err);
    // }
    // async function go() {
    //   // window.doesNotExist();
    //   const pizza = await makePizza(['pineapple']);
    //   console.log(pizza);
    // }
    // go().catch(handleError);

    function handleError(err) {
      console.log('ohhh nooo');
      console.log(err);
    }
    async function go() {
      const pizza = await makePizza(['pineapple']);
      // const pizza = await makePizza(['mushrooms']);
      console.log(pizza); // dj --- when Promises got rejected, will this line execute?
      return pizza;
    }
    // go()
    //   .then((result) => {
    //     console.log(result);
    //   })
    //   .catch(handleError);

    // const result = go().catch(handleError);
    // console.log(result);

    // async function goGo() {
    //   const result = await go();
    // }

    // // goGo();
    // goGo().catch(handleError);

    // catch it at run time
    // go().catch(handleError);

    // make a safe function with a Higher Order Function(HOF)
    function makeSafe(fn, errorHandler) {
      return function () {
        fn().catch(errorHandler);
      };
    }

    const safeGo = makeSafe(go, handleError);
    safeGo();
  </script>
</body>

</html>